on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fskubecr.azurecr.io
        username: ${{ secrets.acr_fskubecr_username }}
        password: ${{ secrets.acr_fskubecr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/bulletin-board" -f  "bulletin-board/Dockerfile" -t fskubecr.azurecr.io/fskubecluster:${{ github.sha }}
        docker push fskubecr.azurecr.io/fskubecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_fskubecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep fskubecluster559a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace fskubecluster559a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: fskubecluster559a
        container-registry-url: fskubecr.azurecr.io
        container-registry-username: ${{ secrets.acr_fskubecr_username }}
        container-registry-password: ${{ secrets.acr_fskubecr_password }}
        secret-name: fskubeclustedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: fskubecluster559a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          fskubecr.azurecr.io/fskubecluster:${{ github.sha }}
        imagepullsecrets: |
          fskubeclustedockerauth